# emall.vn → port 8888
server {
    listen 80;
    server_name emall.vn;

    location / {
        proxy_pass http://host.docker.internal:8888;
    }
}

# seller.emall.vn → port 6789
server {
    listen 80;
    server_name seller.emall.vn;

    location / {
        proxy_pass http://host.docker.internal:6789;
    }
}

# moderator.emall.vn → port 1111
server {
    listen 80;
    server_name moderator.emall.vn;

    location / {
        proxy_pass http://host.docker.internal:1111;
    }
}
