export enum Role {
  CUSTOMER = 'CUSTOMER',
  ADMIN = 'ADMIN',
  SUPPORT = 'SUPPORT',
  WAREHOUSE = 'WAREHOUSE',
  SELLER = 'SELLER',
  SUPER_ADMIN = 'SUPER_ADMIN'
}

export const ADMIN_ROLES: Role[] = [Role.ADMIN, Role.SUPER_ADMIN];
