export const ERROR_CODES = {
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  BAD_REQUEST: 'BAD_REQUEST',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',

  REVIEW_NOT_FOUND: 'REVIEW_NOT_FOUND',
  REVIEW_ALREADY_EXISTS: 'REVIEW_ALREADY_EXISTS',
  REVIEW_MODERATION_REASON_REQUIRED: 'REVIEW_MODERATION_REASON_REQUIRED',

  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',

  PRODUCT_NOT_FOUND: 'PRODUCT_NOT_FOUND',
  PRODUCT_SLUG_EXISTS: 'PRODUCT_SLUG_EXISTS',
  PRODUCT_SKU_CONFLICT: 'PRODUCT_SKU_CONFLICT',

  CART_NOT_FOUND: 'CART_NOT_FOUND',
  CART_ITEM_NOT_FOUND: 'CART_ITEM_NOT_FOUND',
  CART_VERSION_CONFLICT: 'CART_VERSION_CONFLICT',
  CART_QUANTITY_INVALID: 'CART_QUANTITY_INVALID',
  CART_QUANTITY_EXCEEDED: 'CART_QUANTITY_EXCEEDED',
  CART_DEPENDENCY_UNAVAILABLE: 'CART_DEPENDENCY_UNAVAILABLE',

  PAYMENT_NOT_FOUND: 'PAYMENT_NOT_FOUND',
  PAYMENT_ALREADY_CAPTURED: 'PAYMENT_ALREADY_CAPTURED',
  PAYMENT_AMOUNT_MISMATCH: 'PAYMENT_AMOUNT_MISMATCH',
  REFUND_AMOUNT_EXCEEDED: 'REFUND_AMOUNT_EXCEEDED',
  IDEMPOTENCY_CONFLICT: 'IDEMPOTENCY_CONFLICT',
  WEBHOOK_IDEMPOTENCY_CONFLICT: 'WEBHOOK_IDEMPOTENCY_CONFLICT',
  INVALID_PAYMENT_STATUS_TRANSITION: 'INVALID_PAYMENT_STATUS_TRANSITION',
  GATEWAY_CALLBACK_INVALID_SIGNATURE: 'GATEWAY_CALLBACK_INVALID_SIGNATURE',
  PAYMENT_GATEWAY_UNAVAILABLE: 'PAYMENT_GATEWAY_UNAVAILABLE',

  INVENTORY_SKU_NOT_FOUND: 'INVENTORY_SKU_NOT_FOUND',
  INVENTORY_INSUFFICIENT_STOCK: 'INVENTORY_INSUFFICIENT_STOCK',
  INVENTORY_RESERVATION_NOT_FOUND: 'INVENTORY_RESERVATION_NOT_FOUND',
  INVENTORY_RESERVATION_CONFLICT: 'INVENTORY_RESERVATION_CONFLICT',
  INVENTORY_NEGATIVE_STOCK: 'INVENTORY_NEGATIVE_STOCK',
  INVENTORY_INVALID_ADJUSTMENT: 'INVENTORY_INVALID_ADJUSTMENT'
} as const;
