export enum PaymentTransactionType {
  INTENT_CREATED = 'INTENT_CREATED',
  REQUIRES_ACTION = 'REQUIRES_ACTION',
  AUTHORIZED = 'AUTHORIZED',
  CAPTURED = 'CAPTURED',
  FAILED = 'FAILED',
  CANCELLED = 'CANCELLED',
  REFUND_REQUESTED = 'REFUND_REQUESTED',
  REFUND_SUCCEEDED = 'REFUND_SUCCEEDED',
  REFUND_FAILED = 'REFUND_FAILED',
  CHARGEBACK = 'CHARGEBACK',
  WEBHOOK_RECEIVED = 'WEBHOOK_RECEIVED'
}
