export const USER_SERVICE_ERROR_CODES = {
  INTERNAL_ERROR: 'USER_SERVICE_INTERNAL_ERROR',
  VALIDATION_ERROR: 'USER_SERVICE_VALIDATION_ERROR',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_EMAIL_EXISTS: 'USER_EMAIL_EXISTS',
  USER_CREATE_FAILED: 'USER_CREATE_FAILED'
} as const;
