export enum ErrorCode {
  BAD_REQUEST = 'BAD_REQUEST',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  NOT_FOUND = 'NOT_FOUND',
  CONFLICT = 'CONFLICT',
  TOO_MANY_REQUESTS = 'TOO_MANY_REQUESTS',
  VALIDATION_FAILED = 'VALIDATION_FAILED',
  INVALID_SHIPMENT_STATUS_TRANSITION = 'INVALID_SHIPMENT_STATUS_TRANSITION',
  WEBHOOK_IDEMPOTENCY_CONFLICT = 'WEBHOOK_IDEMPOTENCY_CONFLICT',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  SERVICE_UNAVAILABLE = 'SERVICE_UNAVAILABLE'
}
