export enum ErrorCode {
  BAD_REQUEST = 'BAD_REQUEST',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  NOT_FOUND = 'NOT_FOUND',
  CONFLICT = 'CONFLICT',
  VALIDATION_FAILED = 'VALIDATION_FAILED',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  SERVICE_UNAVAILABLE = 'SERVICE_UNAVAILABLE',
  CART_NOT_FOUND = 'CART_NOT_FOUND',
  CART_ITEM_NOT_FOUND = 'CART_ITEM_NOT_FOUND',
  CART_VERSION_CONFLICT = 'CART_VERSION_CONFLICT',
  CART_QUANTITY_INVALID = 'CART_QUANTITY_INVALID',
  CART_QUANTITY_EXCEEDED = 'CART_QUANTITY_EXCEEDED',
  CART_DEPENDENCY_UNAVAILABLE = 'CART_DEPENDENCY_UNAVAILABLE'
}
