export enum Role {
  BUYER = 'BUYER',
  CUSTOMER = 'CUSTOMER',
  SELLER = 'SELLER',
  ADMIN = 'ADMIN',
  MODERATOR = 'MODERATOR',
  SUPPORT = 'SUPPORT',
  WAREHOUSE = 'WAREHOUSE',
  SUPER_ADMIN = 'SUPER_ADMIN'
}

export const BUYER_ROLES: Role[] = [Role.BUYER, Role.CUSTOMER];
