apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  labels:
    app: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      nodeSelector:
        workload: app
      containers:
        - name: order-service
          image: order-service:dev
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
          envFrom:
            - configMapRef:
                name: ecommerce-common-config
            - secretRef:
                name: ecommerce-secrets
          env:
            - name: APP_NAME
              value: order-service
            - name: DATABASE_URL
              value: postgresql://eorder:eorder@postgres:5432/ecommerce_order?sslmode=disable
            - name: DB_MIGRATIONS_RUN
              value: "true"
            - name: MIGRATION_FILE
              value: /migrations/0001_init_order_service.sql
            - name: KAFKA_ENABLED
              value: "false"
            - name: REDIS_ENABLED
              value: "true"
            - name: PRODUCT_SERVICE_BASE_URL
              value: http://product-service:8080/api/v1
            - name: INTERNAL_SERVICE_TOKEN
              value: dev-internal-service-token
          readinessProbe:
            httpGet:
              path: /api/v1/health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 12
          livenessProbe:
            httpGet:
              path: /api/v1/live
              port: http
            initialDelaySeconds: 30
            periodSeconds: 20
            timeoutSeconds: 3
            failureThreshold: 6
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  labels:
    app: order-service
spec:
  type: ClusterIP
  selector:
    app: order-service
  ports:
    - name: http
      port: 8080
      targetPort: http
