apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-service
  labels:
    app: inventory-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-service
  template:
    metadata:
      labels:
        app: inventory-service
    spec:
      nodeSelector:
        workload: app
      containers:
        - name: inventory-service
          image: inventory-service:dev
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
          envFrom:
            - configMapRef:
                name: ecommerce-common-config
            - secretRef:
                name: ecommerce-secrets
          env:
            - name: APP_NAME
              value: inventory-service
            - name: DATABASE_URL
              value: postgresql://einventory:einventory@postgres:5432/ecommerce_inventory?sslmode=disable
            - name: DB_MIGRATIONS_RUN
              value: "false"
            - name: MIGRATION_FILE
              value: /migrations/0001_init_inventory_service.sql
            - name: KAFKA_ENABLED
              value: "true"
            - name: PRODUCT_EVENTS_TOPIC
              value: product.events
            - name: PRODUCT_EVENTS_CONSUMER_GROUP
              value: inventory-service-product-events-group
            - name: RESERVATION_DEFAULT_TTL_MINUTES
              value: "1440"
            - name: REDIS_ENABLED
              value: "true"
          readinessProbe:
            httpGet:
              path: /api/v1/health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 12
          livenessProbe:
            httpGet:
              path: /api/v1/live
              port: http
            initialDelaySeconds: 30
            periodSeconds: 20
            timeoutSeconds: 3
            failureThreshold: 6
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-service
  labels:
    app: inventory-service
spec:
  type: ClusterIP
  selector:
    app: inventory-service
  ports:
    - name: http
      port: 8080
      targetPort: http
