apiVersion: v1
kind: ConfigMap
metadata:
  name: ecommerce-common-config
data:
  APP_ENV: development
  NODE_ENV: development
  PORT: "8080"
  API_PREFIX: api/v1
  REDIS_ENABLED: "true"
  REDIS_URL: redis://redis:6379
  KAFKA_ENABLED: "true"
  KAFKA_BROKERS: kafka:9092
  DB_SSL: "false"
