apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - configmap.yaml
  - data-postgres.yaml
  - data-mongo.yaml
  - data-redis.yaml
  - data-minio.yaml
  - data-kafka.yaml
  - app-auth-service.yaml
  - app-user-service.yaml
  - app-product-service.yaml
  - app-cart-service.yaml
  - app-order-service.yaml
  - app-payment-service.yaml
  - app-inventory-service.yaml
  - app-shipping-service.yaml
  - app-notification-service.yaml
  - app-analytics-service.yaml
  - app-review-service.yaml
  - app-chat-service.yaml
  - app-live-service.yaml
  - app-media-service.yaml
  - app-api-gateway.yaml
  - frontend-buyer-web.yaml
  - frontend-seller.yaml
  - frontend-moderator.yaml
  - ingress.yaml

configMapGenerator:
  - name: postgres-init-sql
    files:
      - init-multiple-dbs.sql=postgres-init-multiple-dbs.sql

generatorOptions:
  disableNameSuffixHash: true
