apiVersion: v1
kind: Secret
metadata:
  name: ecommerce-secrets
  namespace: ecommerce-dev
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: replace-with-strong-postgres-password
  POSTGRES_DB: postgres
  JWT_SECRET: replace-with-shared-jwt-secret-min-32-chars
  JWT_ACCESS_SECRET: replace-with-shared-jwt-secret-min-32-chars
  JWT_REFRESH_SECRET: replace-with-refresh-secret-min-32-chars
  JWT_MFA_SECRET: replace-with-mfa-secret-min-32-chars
  REFRESH_TOKEN_PEPPER: replace-with-pepper-min-16-chars
  GOOGLE_OAUTH_CLIENT_ID: replace-with-google-oauth-client-id
  GOOGLE_OAUTH_CLIENT_SECRET: replace-with-google-oauth-client-secret
