apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ecommerce-dev

resources:
  - ../../base

images:
  - name: api-gateway
    newName: docker.io/truongdevops/api-gateway
    newTag: dev
  - name: auth-service
    newName: docker.io/truongdevops/auth-service
    newTag: dev
  - name: user-service
    newName: docker.io/truongdevops/user-service
    newTag: dev
  - name: product-service
    newName: docker.io/truongdevops/product-service
    newTag: dev
  - name: cart-service
    newName: docker.io/truongdevops/cart-service
    newTag: dev
