apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ecommerce-dev

resources:
- ../../base

images:
- name: analytics-service
  newName: docker.io/vantruong179/ecommerce-microservices-analytics-service
  newTag: 849fc1786fb5
- name: api-gateway
  newName: docker.io/vantruong179/ecommerce-microservices-api-gateway
  newTag: 859e8a69678b
- name: auth-service
  newName: docker.io/vantruong179/ecommerce-microservices-auth-service
  newTag: 6b398ae54c7c
- name: buyer-web
  newName: docker.io/vantruong179/ecommerce-microservices-buyer-web
  newTag: b3474057ea06
- name: cart-service
  newName: docker.io/vantruong179/ecommerce-microservices-cart-service
  newTag: c6479c444309
- name: chat-service
  newName: docker.io/vantruong179/ecommerce-microservices-chat-service
  newTag: d446e72c5a3c
- name: inventory-service
  newName: docker.io/vantruong179/ecommerce-microservices-inventory-service
  newTag: 849fc1786fb5
- name: live-service
  newName: docker.io/vantruong179/ecommerce-microservices-live-service
  newTag: d446e72c5a3c
- name: media-service
  newName: docker.io/vantruong179/ecommerce-microservices-media-service
  newTag: d446e72c5a3c
- name: moderator-web
  newName: docker.io/vantruong179/ecommerce-microservices-moderator-web
  newTag: b3474057ea06
- name: notification-service
  newName: docker.io/vantruong179/ecommerce-microservices-notification-service
  newTag: 849fc1786fb5
- name: order-service
  newName: docker.io/vantruong179/ecommerce-microservices-order-service
  newTag: 859e8a69678b
- name: payment-service
  newName: docker.io/vantruong179/ecommerce-microservices-payment-service
  newTag: 859e8a69678b
- name: product-service
  newName: docker.io/vantruong179/ecommerce-microservices-product-service
  newTag: c6479c444309
- name: review-service
  newName: docker.io/vantruong179/ecommerce-microservices-review-service
  newTag: 6b398ae54c7c
- name: seller-web
  newName: docker.io/vantruong179/ecommerce-microservices-seller-web
  newTag: b3474057ea06
- name: shipping-service
  newName: docker.io/vantruong179/ecommerce-microservices-shipping-service
  newTag: 859e8a69678b
- name: user-service
  newName: docker.io/vantruong179/ecommerce-microservices-user-service
  newTag: 6b398ae54c7c
