apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ecommerce-dev

resources:
- ../../base

images:
- name: analytics-service
  newName: docker.io/vantruong179/ecommerce-microservices-analytics-service
  newTag: 849fc1786fb5
- name: api-gateway
  newName: docker.io/vantruong179/ecommerce-microservices-api-gateway
  newTag: c6479c444309
- name: auth-service
  newName: docker.io/vantruong179/ecommerce-microservices-auth-service
  newTag: 9e1574ea0dd1
- name: buyer-web
  newName: docker.io/vantruong179/ecommerce-microservices-buyer-web
  newTag: c6c07becf0dd
- name: cart-service
  newName: docker.io/vantruong179/ecommerce-microservices-cart-service
  newTag: c6479c444309
- name: chat-service
  newName: docker.io/vantruong179/ecommerce-microservices-chat-service
  newTag: buyer-mobile-prod-20260525
- name: inventory-service
  newName: docker.io/vantruong179/ecommerce-microservices-inventory-service
  newTag: 849fc1786fb5
- name: live-service
  newName: docker.io/vantruong179/ecommerce-microservices-live-service
  newTag: 2ec5cb283720
- name: media-service
  newName: docker.io/vantruong179/ecommerce-microservices-media-service
  newTag: dev
- name: moderator-web
  newName: docker.io/vantruong179/ecommerce-microservices-moderator-web
  newTag: 1c93781c98ac
- name: notification-service
  newName: docker.io/vantruong179/ecommerce-microservices-notification-service
  newTag: 849fc1786fb5
- name: order-service
  newName: docker.io/vantruong179/ecommerce-microservices-order-service
  newTag: 849fc1786fb5
- name: payment-service
  newName: docker.io/vantruong179/ecommerce-microservices-payment-service
  newTag: 849fc1786fb5
- name: product-service
  newName: docker.io/vantruong179/ecommerce-microservices-product-service
  newTag: c6479c444309
- name: review-service
  newName: docker.io/vantruong179/ecommerce-microservices-review-service
  newTag: dev
- name: seller-web
  newName: docker.io/vantruong179/ecommerce-microservices-seller-web
  newTag: c54ed3b7a073
- name: shipping-service
  newName: docker.io/vantruong179/ecommerce-microservices-shipping-service
  newTag: 849fc1786fb5
- name: user-service
  newName: docker.io/vantruong179/ecommerce-microservices-user-service
  newTag: c6479c444309
