FROM node:20-alpine AS deps
WORKDIR /app

COPY package.json ./
RUN npm install

FROM deps AS builder
WORKDIR /app

COPY nest-cli.json tsconfig*.json ./
COPY src ./src
RUN npm run build

FROM node:20-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production

COPY package.json ./
RUN npm install --omit=dev

COPY --from=builder /app/dist ./dist

EXPOSE 3000
CMD ["npm", "run", "start"]
