hostname: rancher.dt-commerce.site
replicas: 1

ingress:
  enabled: true
  ingressClassName: nginx
  tls:
    source: letsEncrypt

letsEncrypt:
  email: admin@dt-commerce.site
  ingress:
    class: nginx
