#!/usr/bin/env bash
set -euo pipefail

NAMESPACE="${NAMESPACE:-ecommerce-dev}"
MONGO_DEPLOYMENT="${MONGO_DEPLOYMENT:-mongo}"
POSTGRES_DEPLOYMENT="${POSTGRES_DEPLOYMENT:-postgres}"
PRODUCT_DATABASE="${PRODUCT_DATABASE:-ecommerce_product}"
INVENTORY_DATABASE="${INVENTORY_DATABASE:-ecommerce_inventory}"
POSTGRES_USER="${POSTGRES_USER:-postgres}"

usage() {
  cat <<'EOF'
Backfill inventory_items for active product variants that do not have stock rows.

Usage:
  ./scripts/backfill-missing-inventory-items-k8s.sh export [output.tsv]
  ./scripts/backfill-missing-inventory-items-k8s.sh apply <reviewed.tsv>

The export file contains:
  sku, product_id, seller_id, product_name, initial_stock, on_hand

Review and replace on_hand with the seller's actual available quantity before
running apply. Existing inventory_items are never overwritten.

Optional environment variables:
  NAMESPACE, MONGO_DEPLOYMENT, POSTGRES_DEPLOYMENT, PRODUCT_DATABASE,
  INVENTORY_DATABASE, POSTGRES_USER
EOF
}

require_command() {
  command -v "$1" >/dev/null 2>&1 || {
    echo "Missing required command: $1" >&2
    exit 1
  }
}

export_missing_items() {
  local output="${1:-/tmp/missing-inventory-items.tsv}"
  local all_products existing_skus
  all_products="$(mktemp)"
  existing_skus="$(mktemp)"
  trap "rm -f '$all_products' '$existing_skus'" EXIT

  kubectl -n "$NAMESPACE" exec "deploy/$MONGO_DEPLOYMENT" -- \
    mongosh "$PRODUCT_DATABASE" --quiet --eval '
function clean(value) {
  return String(value == null ? "" : value).replace(/[\t\r\n]+/g, " ");
}
print(["sku", "product_id", "seller_id", "product_name", "initial_stock", "on_hand"].join("\t"));
db.products.aggregate([
  {$match: {status: "ACTIVE", deletedAt: null}},
  {$unwind: "$variants"},
  {$project: {
    _id: 0,
    sku: "$variants.sku",
    product_id: {$toString: "$_id"},
    seller_id: "$sellerId",
    product_name: "$name",
    initial_stock: {$ifNull: ["$variants.initialStock", 0]}
  }},
  {$sort: {seller_id: 1, sku: 1}}
]).forEach((row) => {
  const stock = Number.isInteger(row.initial_stock) && row.initial_stock >= 0 ? row.initial_stock : 0;
  print([
    clean(row.sku),
    clean(row.product_id),
    clean(row.seller_id),
    clean(row.product_name),
    stock,
    stock
  ].join("\t"));
});
' > "$all_products"

  kubectl -n "$NAMESPACE" exec "deploy/$POSTGRES_DEPLOYMENT" -- \
    psql -U "$POSTGRES_USER" -d "$INVENTORY_DATABASE" -Atqc \
    "SELECT sku FROM inventory_items ORDER BY sku;" > "$existing_skus"

  awk -F $'\t' '
    NR == FNR { existing[$1] = 1; next }
    FNR == 1 || !($1 in existing) { print }
  ' "$existing_skus" "$all_products" > "$output"

  local missing_count
  missing_count="$(( $(wc -l < "$output") - 1 ))"
  if (( missing_count < 0 )); then
    missing_count=0
  fi
  echo "Exported $missing_count missing active SKU(s) to $output"
  echo "Review column on_hand before applying. It must be actual stock, not an assumed default."
  column -t -s $'\t' "$output" 2>/dev/null || cat "$output"
}

apply_reviewed_items() {
  local input="${1:-}"
  [[ -n "$input" && -f "$input" ]] || {
    echo "Provide an existing reviewed TSV file to apply." >&2
    usage >&2
    exit 1
  }

  local load_file
  load_file="$(mktemp)"
  trap "rm -f '$load_file'" EXIT

  awk -F $'\t' -v OFS=$'\t' '
    NR == 1 {
      if ($1 != "sku" || $2 != "product_id" || $3 != "seller_id" || $6 != "on_hand") {
        print "Unexpected TSV header. Use a file generated by export." > "/dev/stderr"
        exit 1
      }
      print "sku", "product_id", "seller_id", "on_hand"
      next
    }
    NF >= 6 { print $1, $2, $3, $6 }
  ' "$input" > "$load_file"

  {
    cat <<'SQL'
BEGIN;
CREATE TEMP TABLE inventory_backfill_source (
  sku varchar(64) NOT NULL,
  product_id varchar(128) NOT NULL,
  seller_id uuid NOT NULL,
  on_hand integer NOT NULL
) ON COMMIT DROP;
COPY inventory_backfill_source (sku, product_id, seller_id, on_hand)
FROM STDIN WITH (FORMAT csv, DELIMITER E'\t', HEADER true);
SQL
    cat "$load_file"
    cat <<'SQL'
\.

DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM inventory_backfill_source
    WHERE btrim(sku) = '' OR btrim(product_id) = '' OR on_hand < 0
  ) THEN
    RAISE EXCEPTION 'reviewed inventory file contains blank identifiers or negative on_hand';
  END IF;

  IF EXISTS (
    SELECT sku FROM inventory_backfill_source
    GROUP BY sku HAVING count(*) > 1
  ) THEN
    RAISE EXCEPTION 'reviewed inventory file contains duplicate SKU values';
  END IF;

  IF EXISTS (
    SELECT 1
    FROM inventory_backfill_source src
    JOIN inventory_items item ON item.sku = src.sku
    WHERE item.product_id <> src.product_id OR item.seller_id <> src.seller_id
  ) THEN
    RAISE EXCEPTION 'an existing SKU is linked to a different product or seller';
  END IF;
END
$$;

WITH created AS (
  INSERT INTO inventory_items (sku, product_id, seller_id, on_hand, reserved)
  SELECT src.sku, src.product_id, src.seller_id, src.on_hand, 0
  FROM inventory_backfill_source src
  LEFT JOIN inventory_items item ON item.sku = src.sku
  WHERE item.sku IS NULL
  ON CONFLICT (sku) DO NOTHING
  RETURNING sku, on_hand
)
INSERT INTO inventory_movements (
  sku,
  order_id,
  movement_type,
  delta_on_hand,
  delta_reserved,
  reason,
  actor_id,
  actor_role,
  request_id
)
SELECT
  sku,
  NULL,
  'ADJUST',
  on_hand,
  0,
  'Backfill missing inventory for active product variant',
  '00000000-0000-0000-0000-000000000000',
  'SUPER_ADMIN',
  'bf-' || substr(md5(sku || '-active-product'), 1, 24)
FROM created;

SELECT
  src.sku,
  item.product_id,
  item.seller_id,
  item.on_hand,
  item.reserved,
  item.on_hand - item.reserved AS available
FROM inventory_backfill_source src
JOIN inventory_items item ON item.sku = src.sku
ORDER BY src.sku;
COMMIT;
SQL
  } | kubectl -n "$NAMESPACE" exec -i "deploy/$POSTGRES_DEPLOYMENT" -- \
    psql -v ON_ERROR_STOP=1 -U "$POSTGRES_USER" -d "$INVENTORY_DATABASE" -P pager=off
}

main() {
  require_command kubectl

  case "${1:-}" in
    export)
      export_missing_items "${2:-}"
      ;;
    apply)
      apply_reviewed_items "${2:-}"
      ;;
    -h|--help|help|"")
      usage
      ;;
    *)
      echo "Unknown action: $1" >&2
      usage >&2
      exit 1
      ;;
  esac
}

main "$@"
