{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "ecommerce.fullname" . }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          {{- range $name, $svc := .Values.services }}
          {{- if and $svc.enabled $svc.path }}
          - path: {{ $svc.path }}
            pathType: Prefix
            backend:
              service:
                name: {{ $name }}
                port:
                  name: http
          {{- end }}
          {{- end }}
{{- end }}
