export enum ErrorCode {
  BAD_REQUEST = 'BAD_REQUEST',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  NOT_FOUND = 'NOT_FOUND',
  CONFLICT = 'CONFLICT',
  VALIDATION_FAILED = 'VALIDATION_FAILED',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  SERVICE_UNAVAILABLE = 'SERVICE_UNAVAILABLE',
  INVENTORY_SKU_NOT_FOUND = 'INVENTORY_SKU_NOT_FOUND',
  INVENTORY_INSUFFICIENT_STOCK = 'INVENTORY_INSUFFICIENT_STOCK',
  INVENTORY_RESERVATION_NOT_FOUND = 'INVENTORY_RESERVATION_NOT_FOUND',
  INVENTORY_RESERVATION_CONFLICT = 'INVENTORY_RESERVATION_CONFLICT',
  INVENTORY_NEGATIVE_STOCK = 'INVENTORY_NEGATIVE_STOCK',
  INVENTORY_INVALID_ADJUSTMENT = 'INVENTORY_INVALID_ADJUSTMENT'
}
